== Subject

The subject of this Engineering Report (ER) is a hackathon event that was held from June 20th to 21st, 2019 to advance the development of OGC Application Programming Interface (API) specifications. An API is a standard set of documented and supported functions and procedures that expose the capabilities or data of an operating system, application or service to other applications (adapted from ISO/IEC TR 13066-2:2016). The OGC API Hackathon 2019, as the event was called, was hosted by the Geovation Hub in London, United Kingdom. The event was sponsored by the European Space Agency (ESA) and the Ordnance Survey.

== Executive Summary

// more stuff to add
// •	business value of this Engineering Report to improve interoperability, advance location-based technologies or realize innovations.
// •	recommendations on how to further proceed with the standardisation work
// •	Proposed or agreed follow-on work initiatives

Several technologies and practices have emerged over the past decade that have presented new opportunities for geospatial software developers. Amongst those technologies are Web Application Programming Interfaces (APIs). In order to leverage the capabilities offered by these technologies, the OGC has initiated a body of work to develop draft standards for OGC APIs. At the February 2019 OGC Technical Committee (TC) meeting in Singapore, the TC took a decision to hold a hackathon to help advance many of the draft OGC API standards.

The hackathon was held from June 20th to 21st, 2019, hosted by the Geovation Hub in London, United Kingdom. The European Space Agency (ESA), Ordnance Survey and Geovation sponsored the event. The hackathon was also supported by the US National Geospatial Intelligence Agency (NGA). The goal of the hackathon was to advance the development of OGC API specifications, with the aim of the hackathon being to provide an environment and an opportunity for the geospatial community to achieve this goal. The following objectives were set for the hackathon:

* Develop, deploy and test services/clients that support OGC APIs
* Suggest improvements for a common core
* Define rules/guidance that can be documented
* Validate work that has been completed to date
* Contribute to the GitHub repositories of the draft standards

More than 70 individuals participated in the event. The participants represented 60 organizations; 41 of those organizations are OGC members; one of the organizations is an OGC Alliance Partner and the remaining 18 organizations are non-members. Working collaboratively, the participants formed teams around the draft standards.

During the two-day hackathon, the participants developed, deployed and tested a variety of implementations of OGC APIs. These implementations were from different organizations, including private, public and academic organizations. Suggestions for improvements were made, and in some cases, editors of the standards were able to update the draft standards during the hackathon. Improvements to the common core were discussed, and where possible, agreed on. The work that had previously been done was validated through development and testing. Where the previous work was invalid, suggestions for improvements were identified. Requirements and recommendations were discussed and documented as rules and guidance in the Github repositories of the draft standards. This Engineering Report therefore concludes that the hackathon achieved its goal.

One of the key findings of the hackathon was that the draft OGC API standards are implementable. This was evidenced by the implementations developed by many of the participating organizations at the hackathon. Another key finding is that the 'building-block' principle, adopted by the different draft standards, allows for a common core to be specified. This was evidenced in the use of common capabilities such as `/collection` paths and support for bounding box (BBOX) queries.

It is envisaged that the output of the hackathon will be instrumental to the evolution of OGC web service standards to a modern API-based approach, setting the course for open geospatial standards for the next decade. The output should lead to a solid, common core and advancement of a whole new generation of OGC standards that are flexible in modern IT environments. This does not mean that existing OGC web service standards will fade away. Instead, it means that a new suite of OGC standards will give developers and users the option of leveraging capabilities offered by Web APIs.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization | Role
|Gobe Hobona | Open Geospatial Consortium | Editor
|Scott Simmons | Open Geospatial Consortium | Contributor
|Michael Gordon | Ordnance Survey | Contributor
|Simon Green | Ordnance Survey | Contributor
|Clemens Portele | interactive instruments GmbH | Contributor
|Jorge Samuel Mendes de Jesus | ISRIC - World Soil Information | Contributor
|Peter Baumann | rasdaman GmbH | Contributor
|Francesco	Bartoli | Geobeyond | Contributor
|Dirk Stenger | lat/lon GmbH | Contributor
|Chuck Heazel | Heazeltech LLC | Contributor
|Matthias Mohr | University of Münster | Contributor
|Robin Houtmeyers | Hexagon Geospatial | Contributor
|Jonathan Moules | GeoSeer | Contributor
|Gérald Fenoy | GeoLabs | Contributor
|Brad Hards | Sigma Bravo | Contributor
|Chris Little | Met Office | Contributor
|Yves Coene | Spacebel | Contributor
|Adam Branscomb | Esri UK | Contributor
|Adam Martin | Esri | Contributor
|Joan Maso | CREAF | Contributor
|Stephan Meißl | EOX | Contributor
|Tom Kralidis | Open Source Geospatial Foundation (OSGeo) | Contributor
|Alexander Jacob | Eurac Research | Contributor
|Brian Osborn | CACI | Contributor
|Robert St. John | CACI | Contributor
|Jerome St-Louis | Ecere | Contributor
|TBA | TBA | Contributor
|TBA | TBA | Contributor
|TBA | TBA | Contributor
|TBA | TBA | Contributor
|====================

NOTE: Role = Editor and/or Contributor

// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
