[[Overview]]
== Overview

Section 6 introduces the OGC API Hackathon by describing the challenge, the scenario adopted, and the infrastructure used by the participants. The section also presents overviews of the datasets and services identified to support participants during the Hackathon. The section also presents a list of the organizations represented by the participants.

Section 7 describes each of the OGC API specifications that were involved in the hackathon.

Section 8 presents the solution architecture developed in this hackathon. The section identifies the client and service implementations of the OGC API specifications.

Sections 9 and 10 document the results and provide a summary of the main findings, as well as discussing the experiences and lessons learnt.

Appendix A provides reports from each participating organization, covering their motivation for participating, a description of their implementation of the OGC API specifications, alternative approaches, their experiences, impressions and recommendations.
