[[EsriUK]]
=== Esri UK

Esri is a provider of Geographic Information Systems (GIS) software and solutions to a wide range of organizations. Esri software has been deployed in more than 350,000 organizations, including large cities and many national governments. Esri make ArcGIS mapping and analytics software. 

==== Motivation to Participate

Evolution of the OGC specifications to a modern, developer-friendly API is essential.

==== Implemented Solution

To date Esri have not implemented any of the new draft OGC API standards in their released software. They have however been working on various R&D prototypes of server and client.

==== Proposed Alternatives

TBA

==== Experiences with OGC API Specifications

Esri has been involved in the OGC since its inception, and has widely implemented many other OGC standards in both server and client software. After each ArcGIS product release, the latest core OGC standards with compliance tests are reviewed. Currently, 133 ArcGIS products (multiple versions) have received compliance certifications across 338 OGC implementations.

==== Other Impressions & Recommendations

TBA
