[[Geobeyond]]
=== Geobeyond

Geobeyond is a geospatial software and solutions provider. Geobeyond is involved in the development of the GeoNode open source toolkit. GeoNode is a web-based application and platform for developing solutions for spatial data infrastructures (SDI). Francesco Bartoli represented Geobeyond at the hackathon.

==== Motivation to Participate

Geobeyond was motivated to participate in the hackathon by:

* the potential to port the https://github.com/francbartoli/gee-bridge[GEE-Bridge API] to OGC API - Commons and OGC API - Processes.
* discussion within the community on how to handle WPS remote processes and process chaining (local and remote).
* the need to understand and find a way to implement several specifications together for the new GeoNode API 4.0 which will be driven by the API-first approach and totally based on the OpenAPI v3 specification.
* alignment with the CSW community about the new OpenAPI based specification.

==== Implemented Solution

During the hackathon, Geobeyond implemented a draft https://github.com/geobeyond/geonode-api/tree/processes[GeoNode API] based on:

 * OGC API - Processes specification which could provide a generic solution for algorithms as functions.
 ** Implemented interface with out-of-the-box validation for jobs and result as modeled in the WPS REST Binding
 ** Support of asynchronous processing and jobs persistence
 ** Deploy ready for containers to Docker Swarm

This starting point will be the base building block to add more specifications to the next GeoNode 4.0 in order to be a reference implementation with at least the following OGC standards:

 * OGC API - Commons standard
 * OGC API - Features standard
 * OGC API – Coverages standard
 * OGC API – Map Tiles standard

==== Proposed Alternatives

The following considerations of alternative approaches were identified by Geobeyond:

* Process chaining and consequently workflows should be part of the perimeter of the specification or can be an abstract concept within GeoNode?
* Processing from cloud infrastructure (Google Earth Engine, IBM Geoscope, etc) have to be considered remote or local? Sort of WPS Cascading?

==== Experiences with OGC API Specifications

Geobeyond has experience with the following OGC API Specifications:

* Basic experience with OGC API - Features
* Basic experience with OGC API - Commons and OGC API - Processes

==== Other Impressions & Recommendations

The event has been pretty much useful and productive and the expectations are to see this kind of developer oriented meetings organized more frequently.
