[[GeoCatBV]]
=== GeoCat B.V.

Established in the Netherlands in 2007, GeoCat (https://www.geocat.net) offers cutting-edge customized software and services that make publishing geospatial data on the Internet easier and more efficient. Operating in the fast growing market of Spatial Data Infrastructures (SDI) and geospatial-enabled technologies. GeoCat builds sustainable applications following the Free and Open Source Software (FOSS) philosophy and open standards.

Therefore, GeoCat has provided successful consulting services and products that contributed to the development of National Spatial Data Infrastructures for The Netherlands, Switzerland, Norway, Sweden, Finland, Denmark, Scotland, The European Environment Agency, Eurostat and many others.

==== Motivation to Participate

GeoCat has been an active supporter of OGC and OGC standards continuously. Working with SDI, especially with geospatial catalogues, GeoCat implemented a wide range of OGC standards. GeoCat participated in the GeoNovum testbed for spatial data on the web, from which results were contributed to the final report of the OGC/W3C best practice for spatial data on the web report. Which was taken as the base for the OGC API developments. Having the OGC standards able to connect to standards in the web domain enlarges the audience of spatial data, but also allows us to benefit from research on standards in those domains.

There are a number of focuses for GeoCat, especially related to GeoNetwork (https://www.geonetwork-opensource.org), in such events:
- We're looking forward to participate in the next generation of UML, YAML & RDF models for spatial data and how they are exchanged in the scope of OGC API's.
- To collect experience and contribute the discussion to implement support for OAPI Catalog, OAPI Tiles and OAPI Features specifications.
- Research how existing client tooling (QGIS, OpenLayers, PowerBI, Talend) can benefit from OGC API standards
- Enable crawling by search engines (and humans) of OGC API's, preferably using (extensions to) common ontologies, such as schema.org, dcat, etc.

==== Implemented Solution

GeoCat contributes to the pygeoapi project, focussing on dataset discovery.
GeoCat is evaluating how to integrate OAPI Catalog into the GeoNetwork catalog product.
GeoCat did a pilot to introduce an OAPI Features client in GeoNetwork. 

==== Experiences with OGC API Specifications

GeoCat has been constantly an active supporter of OGC and OGC standards, including recent efforts on WFS 3.0.

==== Other Impressions & Recommendations

There was an admirable motivation into creating standards easy to understand and simple. On the other hand, valid remarks were raised on being so strict on OGC API on collection concepts, especially when applied to concepts like processes. This could potentially bring a lower adoption of such standards, also considering the remarkable maturity level.
