[[GeoLabs]]
=== GeoLabs

GeoLabs (http://www.geolabs.fr) is a world-wide provider of geospatial management solutions based on open source technologies. GeoLabs is involved in the development of numerous open source geospatial projects, as well as providing Software-as-a-Service (SaaS) and Platform-as-a-Service (PaaS) solutions for geospatial data. GeoLabs has developed MapMint (mapmint.com), a complete web based web mapping infrastructure, participated in the development of geoportail.fr, and the development of Senegal’s National Cadastre. Further, GeoLabs provides commercial cloud-based GIS services, and contributes in numerous open source projects.

==== Motivation to Participate

The motivation for GeoLabs was to get more information about the direction followed by the working groups for the different standards, as well as to get answers to some questions that GeoLabs had about the OGC API - Processes specification. Indeed, GeoLabs implemented part of the OGC API - Processes specification before attending the hackathon and encountered some issues in trying to mimic the different options available in WPS 2.0. The hackathon therefore provided an opportunity for GeoLabs to discuss and share experiences with participants from other organizations.

==== Implemented Solution

GeoLabs came to the hackathon with the ZOO-Project implementation demonstration swagger interface available at: https://demo.mapmint.com/swagger-ui/dist/ for interacting with two instances based on the OGC API - Processes specification. The instances are available at: http://demo.mapmint.com/WPS2/ and  http://demo.mapmint.com/WPS3/ (where the former is using the model available on the https://github.com/opengeospatial/wps-rest-binding[wps-rest-binding] repository and the latter one is based on the tests GeoLabs made to change the wps-rest-binding, in order to make it fit the current WPS 2.0 definitions).

This implementation of the OGC API - Processes specification is based on the one available at http://www.zoo-project.org with some modifications. It is based on an implementation that is able to offer access to libraries and applications such as GDAL, OGR, GEOS, PROJ,  the Orfeo ToolBox (https://www.orfeo-toolbox.org/) and the SAGA-GIS application. The demonstration includes numerous services available to be run using the implementation of the OGC API - Processes specification.

==== Proposed Alternatives

TBA

==== Experiences with OGC API Specifications

TBA

==== Other Impressions & Recommendations

TBA
